package dev.hg.etchlog.core;

import dev.hg.etchlog.core.hash.MerkleHash;
import dev.hg.etchlog.core.proof.ConsistencyProof;
import dev.hg.etchlog.core.proof.InclusionProof;
import dev.hg.etchlog.core.sth.Ed25519SthSigner;
import dev.hg.etchlog.core.tree.MerkleTreeHash;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.security.spec.NamedParameterSpec;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.StringJoiner;
import org.junit.jupiter.api.Test;

/**
 * Emits the shared cross-implementation test vectors consumed by the dashboard's TypeScript
 * verifier parity test ({@code dashboard/src/verifier/parity.test.ts}). These vectors are the
 * contract: the in-browser verifier must agree with {@code etchlog-core} on every one of them.
 *
 * <p><strong>Not a unit test.</strong> Its name deliberately omits the {@code Test}/{@code Tests}
 * suffix so the surefire {@code <includes>} pattern never runs it during {@code mvn verify} (which
 * would rewrite the committed fixture on every build). Regenerate the fixture only when the core
 * hashing/proof/STH encoding changes, with:
 *
 * <pre>
 *   ./mvnw -q -pl etchlog-core test -Dtest=CoreVectorGenerator -DfailIfNoTests=false
 * </pre>
 *
 * The generator also self-checks every emitted vector against the core verifiers before writing, so
 * a corrupt fixture can never be produced.
 */
public class CoreVectorGenerator {

    private static final Base64.Encoder B64 = Base64.getEncoder();
    private static final int MAX_SIZE = 9; // covers powers of two and ragged sizes (1..9)
    private static final long FIXED_TIMESTAMP_MS = 1_750_000_000_000L;
    private static final Path OUTPUT =
            Path.of("..", "dashboard", "src", "verifier", "__fixtures__", "core-vectors.json");

    @Test
    void generate() throws Exception {
        // Deterministic leaf payloads so the leaf/root hashes are stable across regenerations.
        List<byte[]> payloads = new ArrayList<>();
        for (int i = 0; i < MAX_SIZE; i++) {
            payloads.add(("etchlog-leaf-" + i).getBytes(StandardCharsets.UTF_8));
        }
        List<byte[]> leafHashes = new ArrayList<>();
        for (byte[] p : payloads) {
            leafHashes.add(MerkleHash.hashLeaf(p));
        }

        StringBuilder json = new StringBuilder();
        json.append("{\n");
        json.append(
                "  \"_comment\": \"Generated by CoreVectorGenerator. Do not edit by hand.\",\n");
        json.append("  \"emptyTreeRoot\": \"")
                .append(b64(MerkleHash.emptyTreeHash()))
                .append("\",\n");

        // Leaves: raw payload + RFC 6962 leaf hash.
        json.append("  \"leaves\": [\n");
        StringJoiner leafJoin = new StringJoiner(",\n");
        for (int i = 0; i < MAX_SIZE; i++) {
            leafJoin.add(
                    "    {\"leafData\": \""
                            + b64(payloads.get(i))
                            + "\", \"leafHash\": \""
                            + b64(leafHashes.get(i))
                            + "\"}");
        }
        json.append(leafJoin).append("\n  ],\n");

        // Roots (MTH) for every tree size 1..MAX_SIZE.
        json.append("  \"roots\": [\n");
        StringJoiner rootJoin = new StringJoiner(",\n");
        for (int n = 1; n <= MAX_SIZE; n++) {
            byte[] root = MerkleTreeHash.mth(leafHashes.subList(0, n));
            rootJoin.add("    {\"treeSize\": " + n + ", \"root\": \"" + b64(root) + "\"}");
        }
        json.append(rootJoin).append("\n  ],\n");

        // Inclusion proofs: every (leafIndex, treeSize) with 0 <= leafIndex < treeSize.
        json.append("  \"inclusion\": [\n");
        StringJoiner incJoin = new StringJoiner(",\n");
        for (int n = 1; n <= MAX_SIZE; n++) {
            List<byte[]> sub = leafHashes.subList(0, n);
            byte[] root = MerkleTreeHash.mth(sub);
            for (int i = 0; i < n; i++) {
                List<byte[]> path = InclusionProof.generate(sub, i, n);
                // Self-check before emitting.
                if (!dev.hg.etchlog.core.proof.InclusionVerifier.verify(
                        leafHashes.get(i), i, n, path, root)) {
                    throw new IllegalStateException(
                            "inclusion self-check failed at i=" + i + " n=" + n);
                }
                incJoin.add(
                        "    {\"leafIndex\": "
                                + i
                                + ", \"treeSize\": "
                                + n
                                + ", \"root\": \""
                                + b64(root)
                                + "\", \"auditPath\": ["
                                + b64Array(path)
                                + "]}");
            }
        }
        json.append(incJoin).append("\n  ],\n");

        // Consistency proofs: every (m, n) with 1 <= m <= n <= MAX_SIZE.
        json.append("  \"consistency\": [\n");
        StringJoiner conJoin = new StringJoiner(",\n");
        for (int n = 1; n <= MAX_SIZE; n++) {
            byte[] newRoot = MerkleTreeHash.mth(leafHashes.subList(0, n));
            for (int m = 1; m <= n; m++) {
                byte[] oldRoot = MerkleTreeHash.mth(leafHashes.subList(0, m));
                List<byte[]> proof = ConsistencyProof.generate(leafHashes.subList(0, n), m, n);
                if (!dev.hg.etchlog.core.proof.ConsistencyVerifier.verify(
                        m, n, oldRoot, newRoot, proof)) {
                    throw new IllegalStateException(
                            "consistency self-check failed at m=" + m + " n=" + n);
                }
                conJoin.add(
                        "    {\"first\": "
                                + m
                                + ", \"second\": "
                                + n
                                + ", \"oldRoot\": \""
                                + b64(oldRoot)
                                + "\", \"newRoot\": \""
                                + b64(newRoot)
                                + "\", \"proof\": ["
                                + b64Array(proof)
                                + "]}");
            }
        }
        json.append(conJoin).append("\n  ],\n");

        // A signed STH over the full tree. The Ed25519 key pair is derived from a fixed seed so the
        // committed fixture's public key and signature are byte-stable across regenerations — a
        // fresh random key would rewrite the fixture on every run and silently break the TS parity
        // test until re-committed. The public key is derived from the seed by deterministic curve
        // math, so the pair is identical on every JDK. The public key (SPKI PEM) is the only
        // material the TS verifier needs to validate the signature.
        KeyPairGenerator kpg = KeyPairGenerator.getInstance("Ed25519");
        kpg.initialize(NamedParameterSpec.ED25519, deterministicRandom());
        KeyPair kp = kpg.generateKeyPair();
        int sthSize = MAX_SIZE;
        byte[] sthRoot = MerkleTreeHash.mth(leafHashes.subList(0, sthSize));
        Ed25519SthSigner signer = new Ed25519SthSigner(kp.getPrivate());
        byte[] signature = signer.sign(sthSize, FIXED_TIMESTAMP_MS, sthRoot);
        String publicKeyPem = toPem(kp.getPublic().getEncoded());

        json.append("  \"sth\": {\n");
        json.append("    \"treeSize\": ").append(sthSize).append(",\n");
        json.append("    \"rootHash\": \"").append(b64(sthRoot)).append("\",\n");
        json.append("    \"timestamp\": ").append(FIXED_TIMESTAMP_MS).append(",\n");
        json.append("    \"signature\": \"").append(b64(signature)).append("\",\n");
        json.append("    \"publicKeyPem\": ").append(jsonString(publicKeyPem)).append("\n");
        json.append("  }\n");
        json.append("}\n");

        Files.createDirectories(OUTPUT.getParent());
        Files.writeString(OUTPUT, json.toString());
        System.out.println(
                "Wrote shared verifier vectors to " + OUTPUT.toAbsolutePath().normalize());
    }

    /**
     * A deterministic {@link SecureRandom} backed by a SHA-256 counter stream over a fixed seed.
     * Used solely to make the fixture's STH key pair reproducible across regenerations; it is NOT a
     * secure RNG and must never be used for anything but generating these test vectors.
     */
    private static SecureRandom deterministicRandom() throws NoSuchAlgorithmException {
        final MessageDigest md = MessageDigest.getInstance("SHA-256");
        return new SecureRandom() {
            private byte[] block =
                    md.digest(
                            "etchlog-core-vector-fixture-key-v1".getBytes(StandardCharsets.UTF_8));
            private int offset = 0;

            @Override
            public void nextBytes(byte[] bytes) {
                for (int i = 0; i < bytes.length; i++) {
                    if (offset >= block.length) {
                        block = md.digest(block);
                        offset = 0;
                    }
                    bytes[i] = block[offset++];
                }
            }
        };
    }

    private static String b64(byte[] bytes) {
        return B64.encodeToString(bytes);
    }

    private static String b64Array(List<byte[]> items) {
        StringJoiner j = new StringJoiner(", ");
        for (byte[] b : items) {
            j.add("\"" + b64(b) + "\"");
        }
        return j.toString();
    }

    /** PEM-wrap an SPKI DER public key with 64-char base64 lines. */
    private static String toPem(byte[] der) {
        String body =
                Base64.getMimeEncoder(64, "\n".getBytes(StandardCharsets.UTF_8))
                        .encodeToString(der);
        return "-----BEGIN PUBLIC KEY-----\n" + body + "\n-----END PUBLIC KEY-----\n";
    }

    /** JSON-escape a string (handles the newlines in the PEM). */
    private static String jsonString(String s) {
        StringBuilder sb = new StringBuilder("\"");
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            switch (c) {
                case '"' -> sb.append("\\\"");
                case '\\' -> sb.append("\\\\");
                case '\n' -> sb.append("\\n");
                case '\r' -> sb.append("\\r");
                case '\t' -> sb.append("\\t");
                default -> sb.append(c);
            }
        }
        return sb.append("\"").toString();
    }
}
